name: BirnaloniaSystem
version: '${project.version}'
main: de.buuddyyy.birnaloniasystem.BirnaloniaSystemPlugin
api-version: '1.20'
author: buuddyyy
commands:
  chestlock:
    aliases: [cl]
  enderchest:
    aliases: [ec]
  home:
  sethome:
  setspawn:
  spawn: